# Generated by Django 2.0.2 on 2018-11-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='contact',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c', to='cmdb_master.UserGroup', verbose_name='业务组'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m', to='cmdb_master.UserProfile', verbose_name='系统管理员'),
        ),
    ]
