# Generated by Django 2.0.2 on 2018-11-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_master', '0002_auto_20181126_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='描述'),
        ),
    ]
