# Generated by Django 2.0.2 on 2018-11-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_master', '0003_tag_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='标签')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '标签表',
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='tag',
            field=models.ManyToManyField(to='cmdb_master.Tago'),
        ),
    ]
