# Generated by Django 2.0.2 on 2018-11-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_master', '0004_auto_20181126_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tago',
        ),
    ]
