# Generated by Django 2.0.2 on 2018-11-27 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_master', '0006_auto_20181126_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.CharField(max_length=32, verbose_name='核心数')),
                ('capacity', models.IntegerField(default=192, verbose_name='占用')),
                ('server_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CPU', to='cmdb_master.Server')),
            ],
            options={
                'verbose_name_plural': 'CPU负载',
            },
        ),
        migrations.RemoveField(
            model_name='disk',
            name='pd_type',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='ipaddrs',
        ),
        migrations.AddField(
            model_name='disk',
            name='desc',
            field=models.IntegerField(blank=True, default=192, null=True, verbose_name='介绍'),
        ),
        migrations.AddField(
            model_name='disk',
            name='persent',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='已用百分比'),
        ),
        migrations.AddField(
            model_name='disk',
            name='used',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='已用'),
        ),
        migrations.AddField(
            model_name='memory',
            name='desc',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='介绍'),
        ),
        migrations.AddField(
            model_name='memory',
            name='persent',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='已用比例'),
        ),
        migrations.AddField(
            model_name='memory',
            name='used',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='已用'),
        ),
        migrations.AddField(
            model_name='nic',
            name='ifDesc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='nic',
            name='ifMtu',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='MTU'),
        ),
        migrations.AddField(
            model_name='nic',
            name='ifSpeed',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='速率'),
        ),
        migrations.AddField(
            model_name='nic',
            name='ifType',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='nic',
            name='ipAddr',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='网卡IP地址'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='总空间'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='model',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='hwaddr',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='网卡mac地址'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='netmask',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='nic',
            name='up',
            field=models.BooleanField(default=True),
        ),
    ]
